baseURL: https://drgoldsby.vet

languageCode: en-us
title: "Dr. Goldsby"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable Google Analytics
googleAnalytics: UA-135069512-1

# Enable Disqus forum
disqusShortname: alexbezek

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:

  # background image of the landing page
  background: "images/background.jpg"

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will be default to the theme logos if not provided.
  logo:
    # main: "images/logo/logo.png"
    # inverted: "images/logo/logo.png"
    # favicon: "images/logo/logo.png"

  # GitHub repo URL of your site (used for <Improve This Page> Button)
  gitRepo: https://github.com/alex-bezek/kittys-site

  # specify whether you want to write blog post or not
  enableBlogPost: false

  # specify whether you want to show Table of Contents in reading page
  enableTOC: false

  # specify the list of custom menus that you want to show in the top navbar.
  # they will be separated by a divider from the main menus.
  # customMenus:
  # - name: Notes
  #   url: https://hossainnotes.netlify.app/docs/example/

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false